name: "cloud-file-storage-dev"

services:
  mysql:
    image: mysql:8.4.7
    container_name: cloud-file-storage-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3306:3306"

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioroot
    command: [ "server", "/data", "--console-address", ":9001" ]
    ports:
      - "9000:9000"
      - "9001:9001"
