name: "cloud-file-storage"

services:
  mysql:
    image: mysql:8.4.7
    container_name: cloud-file-storage-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "${SPRING_DATASOURCE_USERNAME}", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - cloud-file-storage-data:/var/lib/mysql

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DB: ${SPRING_DATASOURCE_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  cloud-file-storage-data:
  redis-data:
  minio-data: