spring:

  datasource:
    url: jdbc:mysql://localhost:3306/cloud-file-storage
    username: root
    password: root

  data:
    redis:
      password: root
      port: 6379

minio:
  client:
    endpoint: http://localhost:9000
    user: minio
    password: minioroot
    bucket-name: user-files