spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  session:
    timeout: 1h

minio:
  client:
    endpoint: ${MINIO_ENDPOINT}
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
    bucket-name: ${MINIO_BUCKET_NAME}